// Standard labor activities crews punch against (buffered mode). Seeded from
// the org's JobTread labor cost codes (100-135 series). Managers reconcile
// these to actual budget cost items in the review dashboard before pushing.
export const DEFAULT_ACTIVITIES = [
  'Supervisor',
  'General Labor - Heavy',
  'General Labor - Light',
  'General Framer',
  'Mason',
  'Plumber',
  'Electrician',
  'HVAC',
  'General Demolition',
  'Painter',
  'Finish Carpentry',
  'Drywaller',
  'Taper',
  'Concrete Finisher',
  'Concrete Labor',
  'Equipment & Operator',
  'Hauling',
  'Landscaping',
  'Sider',
  'Sheet Metal',
  'Scaffold Erector',
  'Scaffold Labor',
  'Roofer Residential',
  'Commercial Roofer',
  'Building Layout',
  'Steel Worker',
  'Shop Time',
  'Insulation Installer',
  'Paperwork / Admin',
  'Ironwork',
  'Rebar',
  'Conduit',
  'Remediation Technician',
  'Tile / Cultured Marble Installer',
  'Craftsman',
];
